Cidetsi\GestionesBundle\Entity\Gestion:
    type: entity
    table: gestion
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 128
            unique: true
            nullable: false
        status:
            type: string
            columnDefinition: ENUM('enabled', 'disabled', 'active')
            nullable: false
            options:
                default: 'disabled'
    uniqueConstraints:
        code:
            columns: [ name ]
    lifecycleCallbacks: {}
