base:
    resource: "@CidetsiBaseBundle/Resources/config/routing.yml"
    prefix:   /
departamentos:
    resource: "@CidetsiDepartamentosBundle/Resources/config/routing/departamento.yml"
    prefix:   /departamentos
carreras:
    resource: "@CidetsiDepartamentosBundle/Resources/config/routing/carrera.yml"
    prefix:   /carreras
planes:
    resource: "@CidetsiDepartamentosBundle/Resources/config/routing/plan_estudio.yml"
    prefix:   /planes
materias:
    resource: "@CidetsiMateriasBundle/Resources/config/routing/materia.yml"
    prefix:   /materias
docentes:
    resource: "@CidetsiDocentesBundle/Resources/config/routing/docente.yml"
    prefix:   /docentes
gestiones:
    resource: "@CidetsiGestionesBundle/Resources/config/routing/gestion.yml"
    prefix:   /gestiones
pdf_report:
    resource: "@CidetsiPdfReportsBundle/Resources/config/routing.yml"
    prefix:   /pdf

