# CidetsiDepartamentoBundle routes
departamento:
    resource: "@CidetsiDepartamentoBundle/Resources/config/routing/departamento.yml"
    prefix:   /departamento
base:
    resource: "@CidetsiBaseBundle/Resources/config/routing.yml"
    prefix:   /
