# CidetsiDepartmentBundle routes
cidetsi_department:
    resource: "@CidetsiDepartmentBundle/Resources/config/routing.yml"
    prefix:   /

# CidetsiBaseBundle routes
cidetsi_base:
    resource: "@CidetsiBaseBundle/Resources/config/routing.yml"
    prefix:   /
