# CidetsiDepartamentoBundle routes
base:
    resource: "@CidetsiBaseBundle/Resources/config/routing.yml"
    prefix:   /
departamento:
    resource: "@CidetsiDepartamentosBundle/Resources/config/routing/departamento.yml"
    prefix:   /departamentos
carrera:
    resource: "@CidetsiDepartamentosBundle/Resources/config/routing/carrera.yml"
    prefix:   /carreras
gestion:
    resource: "@CidetsiGestionesBundle/Resources/config/routing/gestion.yml"
    prefix:   /gestiones
pdf_report:
    resource: "@CidetsiPdfReportsBundle/Resources/config/routing.yml"
    prefix:   /pdf
