base:
    resource: "@CidetsiBaseBundle/Resources/config/routing.yml"
    prefix:   /
departamentos:
    resource: "@CidetsiDepartamentosBundle/Resources/config/routing/departamento.yml"
    prefix:   /departamentos
carreras:
    resource: "@CidetsiDepartamentosBundle/Resources/config/routing/carrera.yml"
    prefix:   /carreras
gestiones:
    resource: "@CidetsiGestionesBundle/Resources/config/routing/gestion.yml"
    prefix:   /gestiones
docentes:
    resource: "@CidetsiDocentesBundle/Resources/config/routing.yml"
    prefix:   /
pdf_report:
    resource: "@CidetsiPdfReportsBundle/Resources/config/routing.yml"
    prefix:   /pdf
