# CidetsiDepartamentoBundle routes
departamento:
    resource: "@CidetsiDepartamentoBundle/Resources/config/routing/departamento.yml"
    prefix:   /departamento
carrera:
    resource: "@CidetsiDepartamentoBundle/Resources/config/routing/carrera.yml"
    prefix:   /carrera
base:
    resource: "@CidetsiBaseBundle/Resources/config/routing.yml"
    prefix:   /
