security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #login:
        #    pattern:  ^/acceder$
        #    security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: base_login
                check_path: base_login_check
            logout:
                path:   base_logout
                target: /

    access_control:
        - { path: ^/acceder, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
#        - { path: ^/departamento, roles: ROLE_ADMIN }
