pdf_test:
    pattern: /test
    defaults: { _controller: CidetsiPdfReportBundle:Default:test }

pdf_seguimiento:
    pattern: /seguimiento
    defaults: { _controller: CidetsiPdfReportBundle:Default:seguimiento }

pdf_nombramiento:
    pattern: /nombramiento
    defaults: { _controller: CidetsiPdfReportBundle:Default:nombramiento }
