Cidetsi\DepartamentoBundle\Entity\Departamento:
    type: entity
    table: departamento
    indexes:
        name_index:
            columns: [ name ]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 128
        abbreviation:
            type: string
            length: 64
        facultad:
            type: string
            length: 128
    uniqueConstraints:
        abbreviation:
            columns: [ abbreviation ]
    oneToMany:
        carreras:
            targetEntity: Carrera
            mappedBy: departamento
            cascade: ["remove"]
    lifecycleCallbacks: {}
#    repositoryClass: Cidetsi\BaseBundle\Entity\DepartamentoRepository
