Cidetsi\DepartamentoBundle\Entity\Departamento:
    type: entity
    table: departamento
    indexes:
        name_index:
            columns: [ name ]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 64
        facultad:
            type: string
            length: 128
    lifecycleCallbacks: {}
#    repositoryClass: Cidetsi\BaseBundle\Entity\DepartamentoRepository
