Cidetsi\DepartamentoBundle\Entity\Departamento:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: abbreviation
    properties:
        name:
            - NotBlank: ~
            - Length: { min: 3, max: 128 }
        abbreviation:
            - NotBlank: ~
            - Length: { min: 3, max: 64 }
        facultad:
            - NotBlank: ~
            - Length: { min: 3, max: 128 }
