Cidetsi\DepartamentoBundle\Entity\Departamento:
    properties:
        name:
            - NotBlank: ~
            - Length: { min: 3, max: 128 }
        abbreviation:
            - NotBlank: ~
            - Length: { min: 3, max: 64 }
        facultad:
            - NotBlank: ~
            - Length: { min: 3, max: 128 }
