Cidetsi\MateriasBundle\Entity\Materia:
    type: entity
    table: materia
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 128
        code:
            type: string
            length: 16
            unique: true
    indexes:
        name_index:
            columns: [ name ]
    uniqueConstraints:
        code:
            columns: [ code ]
    lifecycleCallbacks: {}
